services:
  laa-court-data-end-to-end-tests:
    stdin_open: true # docker run -i
    tty: true # docker run -t

  vcd:
    platform: ${LOCAL_PLATFORM}
    build:
      # TODO: Switch back to main
      context: https://github.com/ministryofjustice/laa-court-data-ui.git#e2e-fixes
      dockerfile: docker/Dockerfile
    pull_policy: always
    volumes:
      - ./tmp/logs/vcd:/usr/src/app/log

  cda:
    platform: ${LOCAL_PLATFORM}
    # TODO: Switch back to main
    build: https://github.com/ministryofjustice/laa-court-data-adaptor.git#e2e-fixes
    pull_policy: always
    volumes:
      - ./tmp/logs/cda:/usr/src/app/log

  mock:
    platform: ${LOCAL_PLATFORM}
    # TODO: Switch back to main
    build: https://github.com/ministryofjustice/hmcts-common-platform-mock-api.git#e2e-fixes
    pull_policy: always
    volumes:
      - ./tmp/logs/mock:/usr/src/app/log
