# This Docker Compose file sets up multiple services for a web application stack.
# The services include a database service (acd-db-services) and 3 application services (vcd, cda and mock).
# The 'start_applications' service uses the 'dockerize' tool to wait for the other services to be available before starting.
# The 'laa-court-data-end-to-end-tests' service runs end-to-end tests for the application.
# Environment variables are used to configure the services, and volumes are used for data persistence.
# This configuration allows for a full-stack application to be run and tested in an isolated environment with consistent IP addresses for inter-service communication.

services:
  start_applications:
    container_name: start_applications
    image: jwilder/dockerize
    command: >
      -wait tcp://cda:3000
      -wait tcp://vcd:3000
      -wait tcp://wiremock:8080
      -wait-retry-interval 10s
      -timeout 300s
    depends_on:
      - cda
      - vcd
      - wiremock

  laa-court-data-end-to-end-tests:
    container_name: laa-court-data-end-to-end-tests
    build: .
    command: sh -c "npm run restore-auth && npm run e2e:smoke-test"
    environment:
      - COOKIES=${COOKIES}
      - VCD_DEV_URL=http://vcd:3000
      - ADMIN_EMAIL=admin@example.com
      - VCD_URL=${VCD_URL:-http://vcd:3000}
      - EMAIL=caseworker@example.com
      - MANAGER_EMAIL=manager@example.com
      - APPEAL_URN=RQ122672778
      - BREACH_URN=OQAC172426
      - URN_WITH_MULTIPLE_HEARINGS=OQAC172426
      - POCA_URN=20NX5872348
    volumes:
      - ./reports:/app/reports
      - ./test-results:/app/test-results

  # DATABASE services

  acd-db-services:
    container_name: acd-db-services
    image: postgres:17.4-alpine
    volumes:
      - ./tmp/pgdata:/var/lib/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acd-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 5432:5432

  cda: &cda
    container_name: cda
    image: ${CDA_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-court-data-adaptor:latest}
    ports:
      - 3002:3000
    command: sh -c "set -e; bundle exec rails db:prepare db:seed; bundle exec rails client:create name=test-app uid=test-app-id secret=test-app-secret; bundle exec puma -C config/puma.rb"
    environment: &cdaenvironment
      RAILS_ENV: development
      ENV: localhost
      RAILS_DEVELOPMENT_HOSTS: cda
      HOSTS: "cda:3000"
      PROTOCOL: http
      COMMON_PLATFORM_URL: http://wiremock:8080/LAA/v1
      SHARED_SECRET_KEY: ${SHARED_SECRET_KEY:-super-secret-key}
      INLINE_SIDEKIQ: 'true'
      DATABASE_URL: postgresql://postgres:postgres@acd-db-services:5432/cda_dev
      MAAT_API_API_URL: ''
      MAAT_API_CLIENT_ID: ''
      MAAT_API_CLIENT_SECRET: ''
      BREACH_COURT_APPLICATIONS: 'true'
    depends_on:
      - acd-db-services
      - wiremock
    volumes:
      - ./tmp/logs/cda:/usr/src/app/log
      
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:3.13.2
    ports:
      - 3003:8080
    command:
      - --verbose
      - --root-dir
      - /home/wiremock
      - --port
      - "8080"
      - --proxy-all=https://apigw.sit.cjscp.org.uk
      - --record-mappings
      - --disable-connection-reuse
      - "true"
      - --proxy-timeout
      - "30000"
      - --disable-http2-tls
    volumes:
      - ./wiremock:/home/wiremock

  vcd: &vcd
    container_name: vcd
    image: ${VCD_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-assess-a-claim/laa-court-data-ui:latest}
    ports:
      - 3001:3000
    command: sh -c "set -e; echo 'setting up db'; bundle exec rails db:prepare db:seed; echo 'starting server'; bundle exec puma"    environment: &vcdenvironment
      RAILS_ENV: development
      ENV: local
      RAILS_DEVELOPMENT_HOSTS: vcd
      HOSTS: "vcd:3000"
      DATABASE_URL: postgresql://postgres:postgres@acd-db-services:5432/vcd_dev
      COURT_DATA_ADAPTOR_API_URL: http://cda:3000/api/internal/v1
      COURT_DATA_ADAPTOR_API_UID: test-app-id
      COURT_DATA_ADAPTOR_API_SECRET: test-app-secret
      FAKE_AUTH: 'true'
      SHOW_LINK_MIGRATED_CASES: 'true'
    depends_on:
      - acd-db-services